service: tests
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2
  memorySize: 128
functions:
  index:
    handler: index.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
