version: '3.1'

services:
    api_1:  
        build: 
            context: ./api_1
        container_name: api_1
        volumes:    
            - "./api_1:/api_1/src/"  
        ports:    
            - "3001:3001"

    api_2:  
        build: 
            context: ./api_2
        container_name: api_2
        volumes:    
            - "./api_2:/api_2/src/"  
        ports:    
            - "3002:3002"